### ISSUE TITLE
CanDestroy not found

### ISSUE THREAD

**Issue by ziplock9000** [xsduan/unity-hierarchy-folders#1]
unity-hierarchy-folders-master/Runtime/Folder.cs(51,70): error CS1061: Type `UnityEngine.GameObject' does not contain a definition for `CanDestroy' and no extension method `CanDestroy' of type `UnityEngine.GameObject' could be found. Are you missing `UnityEngine.Playables' using directive?

Unity 2018.2.13f1

**Comment by xsduan** [comment]
I'm gonna need more context. the method `canDestroy()` is an extension method, have you imported FileEditorUtils.cs? what's your project setup like?

**Comment by ziplock9000** [comment]
The whole unity-hierarchy-folders-master project was included in assets root, therefore unity-hierarchy-folders-master/Runtime/Folders.cs and unity-hierarchy-folders-master/Editor/FolderEditorUtils.cs were both included.

**Comment by xsduan** [comment]
Huh. idk how that got away from me the first time but now it's fixed. does the latest commit work?

(fixed in 1fe13ea oops)

**Comment by ziplock9000** [comment]
Seems to work now, thanks :)
