### ISSUE TITLE
Unity 2020.2 GUID conflicts, cannot compile

### ISSUE THREAD

**Issue by samanabo** [xsduan/unity-hierarchy-folders#19]
I'm attempting to install this package through the package manager via a git url in unity 2020.2.7f1.
Once it is added to the package manager I get the following errors:

`GUID [9b9b359874c54b8e9968bce99b84b1cd] for asset 'Packages/com.xsduan.hierarchy-folders/Editor/Icon Handling.meta' conflicts with:
  'Packages/com.xsduan.hierarchy-folders/Editor/Icons.meta'
We can't assign a new GUID because the asset is in an immutable folder. The asset will be ignored.`

`GUID [d6f29c3d38f5ea94dbfbf44facaeaaca] for asset 'Packages/com.xsduan.hierarchy-folders/Editor/Icon Handling/HierarchyFolderIcon.cs.meta' conflicts with:
  'Packages/com.xsduan.hierarchy-folders/Editor/Icons/HierarchyFolderIcon.cs.meta'
We can't assign a new GUID because the asset is in an immutable folder. The asset will be ignored.`

`GUID [7b9019de4b525b349a48678a64d7983a] for asset 'Packages/com.xsduan.hierarchy-folders/Editor/Icon Handling/ReplaceColor Shader.shader.meta' conflicts with:
  'Packages/com.xsduan.hierarchy-folders/Editor/Icons/ReplaceColor Shader.shader.meta'
We can't assign a new GUID because the asset is in an immutable folder. The asset will be ignored.`

There appears to be an error here for each file in the Editor folder of this package.
Is there something I am doing wrong to import this? or perhaps the meta files need to be updated on the repo since the last update?
Let me know how to proceed. Thanks!

**Comment by SolidAlloy** [comment]
There is a PR that fixes the issue but it is not merged yet: #18.

You can install the package using the following git URL: https://github.com/SolidAlloy/unity-hierarchy-folders.git#guid-duplication-fix

**Comment by xsduan** [comment]
Really sorry, totally forgot about this.

Yup, should be fixed now.
