### ISSUE TITLE
Doesn't work as UPM dependency in Unity 2018.3

### ISSUE THREAD

**Issue by phobos2077** [xsduan/unity-hierarchy-folders#3]
`Script 'Packages/com.xsduan.hierarchy-folders/Runtime/Folder.cs' will not be compiled because it exists outside the Assets folder and does not to belong to any assembly definition file.
UnityEditor.Scripting.ScriptCompilation.EditorCompilationInterface:CompileScripts(EditorScriptCompilationOptions, BuildTargetGroup, BuildTarget)`

**Comment by Bian-Sh** [comment]
Doesn't work as UPM dependency in Unity 2019.2.12F1 as  plugin "com.unity.package-manager -ui " has been changed that much。current version in 2019 is 2.2.0 and there is no "SetPixelData" Function。
