### ISSUE TITLE
EditorOnly prevents working in builds

### ISSUE THREAD

**Issue by soraphis** [xsduan/unity-hierarchy-folders#5]
i just removed the EditorOnly tag (in the OnEnable method) and in the scene and now all my objects are there again.

with the EditorOnly tag on the folder objects my build was an nearly empty world

**Comment by xsduan** [comment]
I'm not quite clear on what you mean. Please clarify what the proper behavior should be, and what it is currently doing, and provide an example scene.

**Comment by soraphis** [comment]
Your extension adds the tag "EditorOnly". objects that are tagged as editor only are ignored by unity in builds.

If i use your folders, and have objects in those folders those objects are missing in the builds.

Unity 2018.3.9f1

______________________________

expected behavior: objects that are stored inside the folder should be available in builds
observed behavior: they are missing

proposed changes: remove the "EditorOnly" tag from this extension.

**Comment by xsduan** [comment]
oh ok i see what you mean now, oops
