### ISSUE TITLE
Create github release v0.1.0

### ISSUE THREAD

**Issue by favoyang** [xsduan/unity-hierarchy-folders#7]
Hi @xsduan,

Thanks for creating the awesome package. Would please create a github release `v0.1.0`? So the package can be included in upcoming openupm registry ([sneak preview](https://beta.openupm.com)), which is a service that build package directly from git tags that conform semver.

**Comment by xsduan** [comment]
I suppose [this](https://github.com/xsduan/unity-hierarchy-folders/releases/tag/v0.1.0) will work?

**Comment by favoyang** [comment]
It works. The package can be preview at https://beta.openupm.com/packages/com.xsduan.hierarchy-folders/ (the serivice is not public ready yet, documentation is basically empty). Further github releases will get published automatically.
